from enum import StrEnum


class Verdict(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    INELIGIBLE = "INELIGIBLE"


class ConditionStatus(StrEnum):
    PASS = "PASS"
    UNKNOWN = "UNKNOWN"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"


class InterestStatus(StrEnum):
    INTERESTED = "INTERESTED"
    ON_HOLD = "ON_HOLD"
    NOT_INTERESTED = "NOT_INTERESTED"


class DownloadStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"


class ExtractionStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    SKIPPED = "SKIPPED"


class DecisionFreshness(StrEnum):
    CURRENT = "CURRENT"
    COMPANY_PROFILE_CHANGED = "COMPANY_PROFILE_CHANGED"
    ANNOUNCEMENT_CHANGED = "ANNOUNCEMENT_CHANGED"
